# Generated by Django 5.1 on 2024-11-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritopedido',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritopedido',
            name='pedido_ingrediente',
        ),
        migrations.RemoveField(
            model_name='historialpedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedidoingrediente',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoingrediente',
            name='ingrediente',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='CarritoPedido',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='HistorialPedido',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='PedidoIngrediente',
        ),
    ]
