# Generated by Django 5.1 on 2024-11-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carrito_carritopedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarritoPedido',
        ),
    ]
