# Generated by Django 5.1 on 2024-09-23 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carrito_carritoingrediente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoingrediente',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritoingrediente',
            name='ingrediente',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='CarritoIngrediente',
        ),
    ]
