# Generated by Django 5.1 on 2024-10-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_carritoingrediente_carrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
