# Generated by Django 5.1 on 2024-11-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_carritopedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpedido',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
