# Generated by Django 5.1 on 2024-11-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carrito'),
        ('app', '0004_usuario_reset_code'),
    ]

    operations = [
    ]
