# Generated by Django 5.1 on 2024-11-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_0004_carrito_0004_usuario_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
